# Generated by Django 3.2.9 on 2021-11-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=200, verbose_name='Street Name')),
                ('date', models.DateTimeField(verbose_name='Article Published Date')),
                ('source', models.CharField(max_length=200, verbose_name='News Source')),
                ('tags', models.CharField(max_length=200, verbose_name='Tags')),
                ('link', models.CharField(max_length=500, verbose_name='Article Link')),
            ],
        ),
    ]
